<a href="https://colab.research.google.com/github/nelsondressler/DragonCaveDS/blob/master/DragonCaveDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **WiDS Datathon 2021 - DragonCaveDS Group**

## Analyzing MITâ€™s GOSSIS's data to determine whether a patient has been diagnosed with *Diabetes Mellitus*.

Members: Henrique Branco, Lorrayne Alberto, Marina Passos

### Data Dictionary:
 
- encounter_id: Whether the patient was invasively ventilated at the time of the highest scoring arterial blood gas using the oxygenation scoring algorithm, including any mode of positive pressure ventilation delivered through a circuit attached to an endo-tracheal tube or tracheostomy;

- hospital_id: Whether the patient was intubated at the time of the highest scoring arterial blood gas used in the oxygenation score;

- age: Whether the patient was admitted to the hospital for an elective surgical operation;

- bmi: Whether the patient has their immune system suppressed within six months prior to ICU admission for any of the following reasons; radiation therapy, chemotherapy, use of non-cytotoxic immunosuppressive drugs, high dose steroids (at least 0.3 mg/kg/day of methylprednisolone or equivalent for at least 6 months).;

- elective_surgery: Whether the patient has cirrhosis and additional complications including jaundice and ascites, upper GI bleeding, hepatic encephalopathy, or coma.;

- ethnicity: Whether the patient has been diagnosed with non-Hodgkin lymphoma.;

- gender: Whether the patient has been diagnosed with diabetes mellitus, a chronic disease.;

- height: Whether the patient has been diagnosed with any solid tumor carcinoma (including malignant melanoma) which has evidence of metastasis.;

- hospital_admit_source: Whether the patient has been diagnosed with acute or chronic myelogenous leukemia, acute or chronic lymphocytic leukemia, or multiple myeloma.;

- icu_admit_source: Whether the patient has a history of heavy alcohol use with portal hypertension and varices, other causes of cirrhosis with evidence of portal hypertension and varices, or biopsy proven cirrhosis. This comorbidity does not apply to patients with a functioning liver transplant.;

- icu_admit_type: Whether the patient has a definitive diagnosis of acquired immune deficiency syndrome (AIDS) (not HIV positive alone);

- icu_id: Whether the patient had acute renal failure during the first 24 hours of their unit stay, defined as a 24 hour urine output <410ml, creatinine >=133 micromol/L and no chronic dialysis;

- icu_stay_type: Whether the Glasgow Coma Scale was unable to be assessed due to patient sedation;

- icu_type: Whether the current unit stay is the second (or greater) stay at an ICU within the same hospitalization;

- pre_icu_los_days: Unique identifier associated with a patient unit stay;

- readmission_status: Unique identifier associated with a hospital;

- weight: The white blood cell count measured during the first 24 hours which results in the highest APACHE III score;

- albumin_apache: The weight (body mass) of the person on unit admission;

- apache_2_diagnosis: The verbal component of the Glasgow Coma Scale measured during the first 24 hours which results in the highest APACHE III score;

- apache_3j_diagnosis: The type of unit admission for the patient;

- apache_post_operative: The total urine output for the first 24 hours;

- arf_apache: The temperature measured during the first 24 hours which results in the highest APACHE III score;

- bilirubin_apache: The sodium concentration measured during the first 24 hours which results in the highest APACHE III score;

- bun_apache: The respiratory rate measured during the first 24 hours which results in the highest APACHE III score;

- creatinine_apache: The pH from the arterial blood gas taken during the first 24 hours of unit admission which produces the highest APACHE III score for acid-base disturbance;

- fio2_apache: The patient's lowest systolic blood pressure during the first hour of their unit stay, non-invasively measured;

- gcs_eyes_apache: The patient's lowest systolic blood pressure during the first hour of their unit stay, invasively measured;

- gcs_motor_apache: The patient's lowest systolic blood pressure during the first hour of their unit stay, either non-invasively or invasively measured;

- gcs_unable_apache: The patient's lowest systolic blood pressure during the first 24 hours of their unit stay, non-invasively measured;

- gcs_verbal_apache: The patient's lowest systolic blood pressure during the first 24 hours of their unit stay, invasively measured;

- glucose_apache: The patient's lowest systolic blood pressure during the first 24 hours of their unit stay, either non-invasively or invasively measured;

- heart_rate_apache: The patient's lowest respiratory rate during the first hour of their unit stay;

- hematocrit_apache: The patient's lowest respiratory rate during the first 24 hours of their unit stay;

- intubated_apache: The patient's lowest peripheral oxygen saturation during the first hour of their unit stay;

- map_apache: The patient's lowest peripheral oxygen saturation during the first 24 hours of their unit stay;

- paco2_apache: The patient's lowest mean blood pressure during the first hour of their unit stay, non-invasively measured;

- paco2_for_ph_apache: The patient's lowest mean blood pressure during the first hour of their unit stay, invasively measured;

- pao2_apache: The patient's lowest mean blood pressure during the first hour of their unit stay, either non-invasively or invasively measured;

- ph_apache: The patient's lowest mean blood pressure during the first 24 hours of their unit stay, non-invasively measured;

- resprate_apache: The patient's lowest mean blood pressure during the first 24 hours of their unit stay, invasively measured;

- sodium_apache: The patient's lowest mean blood pressure during the first 24 hours of their unit stay, either non-invasively or invasively measured;

- temp_apache: The patient's lowest heart rate during the first hour of their unit stay;

- urineoutput_apache: The patient's lowest heart rate during the first 24 hours of their unit stay;

- ventilated_apache: The patient's lowest diastolic blood pressure during the first hour of their unit stay, non-invasively measured;

- wbc_apache: The patient's lowest diastolic blood pressure during the first hour of their unit stay, invasively measured;

- d1_diasbp_invasive_max: The patient's lowest diastolic blood pressure during the first hour of their unit stay, either non-invasively or invasively measured;

- d1_diasbp_invasive_min: The patient's lowest diastolic blood pressure during the first 24 hours of their unit stay, non-invasively measured;

- d1_diasbp_max: The patient's lowest diastolic blood pressure during the first 24 hours of their unit stay, invasively measured;

- d1_diasbp_min: The patient's lowest diastolic blood pressure during the first 24 hours of their unit stay, either non-invasively or invasively measured;

- d1_diasbp_noninvasive_max: The patient's lowest core temperature during the first hour of their unit stay;

- d1_diasbp_noninvasive_min: The patient's lowest core temperature during the first 24 hours of their unit stay;

- d1_heartrate_max: The patient's highest systolic blood pressure during the first hour of their unit stay, non-invasively measured;

- d1_heartrate_min: The patient's highest systolic blood pressure during the first hour of their unit stay, invasively measured;

- d1_mbp_invasive_max: The patient's highest systolic blood pressure during the first hour of their unit stay, either non-invasively or invasively measured;

- d1_mbp_invasive_min: The patient's highest systolic blood pressure during the first 24 hours of their unit stay, non-invasively measured;

- d1_mbp_max: The patient's highest systolic blood pressure during the first 24 hours of their unit stay, invasively measured;

- d1_mbp_min: The patient's highest systolic blood pressure during the first 24 hours of their unit stay, either non-invasively or invasively measured;

- d1_mbp_noninvasive_max: The patient's highest respiratory rate during the first hour of their unit stay;

- d1_mbp_noninvasive_min: The patient's highest respiratory rate during the first 24 hours of their unit stay;

- d1_resprate_max: The patient's highest peripheral oxygen saturation during the first hour of their unit stay;

- d1_resprate_min: The patient's highest peripheral oxygen saturation during the first 24 hours of their unit stay;

- d1_spo2_max: The patient's highest mean blood pressure during the first hour of their unit stay, non-invasively measured;

- d1_spo2_min: The patient's highest mean blood pressure during the first hour of their unit stay, invasively measured;

- d1_sysbp_invasive_max: The patient's highest mean blood pressure during the first hour of their unit stay, either non-invasively or invasively measured;

- d1_sysbp_invasive_min: The patient's highest mean blood pressure during the first 24 hours of their unit stay, non-invasively measured;

- d1_sysbp_max: The patient's highest mean blood pressure during the first 24 hours of their unit stay, invasively measured;

- d1_sysbp_min: The patient's highest mean blood pressure during the first 24 hours of their unit stay, either non-invasively or invasively measured;

- d1_sysbp_noninvasive_max: The patient's highest heart rate during the first hour of their unit stay;

- d1_sysbp_noninvasive_min: The patient's highest heart rate during the first 24 hours of their unit stay;

- d1_temp_max: The patient's highest diastolic blood pressure during the first hour of their unit stay, non-invasively measured;

- d1_temp_min: The patient's highest diastolic blood pressure during the first hour of their unit stay, invasively measured;

- h1_diasbp_invasive_max: The patient's highest diastolic blood pressure during the first hour of their unit stay, either non-invasively or invasively measured;

- h1_diasbp_invasive_min: The patient's highest diastolic blood pressure during the first 24 hours of their unit stay, non-invasively measured;

- h1_diasbp_max: The patient's highest diastolic blood pressure during the first 24 hours of their unit stay, invasively measured;

- h1_diasbp_min: The patient's highest diastolic blood pressure during the first 24 hours of their unit stay, either non-invasively or invasively measured;

- h1_diasbp_noninvasive_max: The patient's highest core temperature during the first hour of their unit stay, invasively measured;

- h1_diasbp_noninvasive_min: The patient's highest core temperature during the first 24 hours of their unit stay, invasively measured;

- h1_heartrate_max: The partial pressure of oxygen from the arterial blood gas taken during the first 24 hours of unit admission which produces the highest APACHE III score for oxygenation;

- h1_heartrate_min: The partial pressure of carbon dioxide from the arterial blood gas taken during the first 24 hours of unit admission which produces the highest APACHE III score for oxygenation;

- h1_mbp_invasive_max: The partial pressure of carbon dioxide from the arterial blood gas taken during the first 24 hours of unit admission which produces the highest APACHE III score for acid-base disturbance;

- h1_mbp_invasive_min: The motor component of the Glasgow Coma Scale measured during the first 24 hours which results in the highest APACHE III score;

- h1_mbp_max: The mean arterial pressure measured during the first 24 hours which results in the highest APACHE III score;

- h1_mbp_min: The lowest white blood cell count for the patient during the first hour of their unit stay;

- h1_mbp_noninvasive_max: The lowest white blood cell count for the patient during the first 24 hours of their unit stay;

- h1_mbp_noninvasive_min: The lowest volume proportion of red blood cells in a patient's blood during the first hour of their unit stay, expressed as a fraction;

- h1_resprate_max: The lowest volume proportion of red blood cells in a patient's blood during the first 24 hours of their unit stay, expressed as a fraction;

- h1_resprate_min: The lowest sodium concentration for the patient in their serum or plasma during the first hour of their unit stay;

- h1_spo2_max: The lowest sodium concentration for the patient in their serum or plasma during the first 24 hours of their unit stay;

- h1_spo2_min: The lowest potassium concentration for the patient in their serum or plasma during the first hour of their unit stay;

- h1_sysbp_invasive_max: The lowest potassium concentration for the patient in their serum or plasma during the first 24 hours of their unit stay;

- h1_sysbp_invasive_min: The lowest platelet count for the patient during the first hour of their unit stay;

- h1_sysbp_max: The lowest platelet count for the patient during the first 24 hours of their unit stay;

- h1_sysbp_min: The lowest lactate concentration for the patient in their serum or plasma during the first hour of their unit stay;

- h1_sysbp_noninvasive_max: The lowest lactate concentration for the patient in their serum or plasma during the first 24 hours of their unit stay;

- h1_sysbp_noninvasive_min: The lowest international normalized ratio for the patient during the first hour of their unit stay;

- h1_temp_max: The lowest international normalized ratio for the patient during the first 24 hours of their unit stay;

- h1_temp_min: The lowest hemoglobin concentration for the patient during the first hour of their unit stay;

- d1_albumin_max: The lowest hemoglobin concentration for the patient during the first 24 hours of their unit stay;

- d1_albumin_min: The lowest glucose concentration of the patient in their serum or plasma during the first hour of their unit stay;

- d1_bilirubin_max: The lowest glucose concentration of the patient in their serum or plasma during the first 24 hours of their unit stay;

- d1_bilirubin_min: The lowest fraction of inspired oxygen for the patient during the first hour of their unit stay;

- d1_bun_max: The lowest fraction of inspired oxygen for the patient during the first 24 hours of their unit stay;

- d1_bun_min: The lowest creatinine concentration of the patient in their serum or plasma during the first hour of their unit stay;

- d1_calcium_max: The lowest creatinine concentration of the patient in their serum or plasma during the first 24 hours of their unit stay;

- d1_calcium_min: The lowest calcium concentration of the patient in their serum during the first hour of their unit stay;

- d1_creatinine_max: The lowest calcium concentration of the patient in their serum during the first 24 hours of their unit stay;

- d1_creatinine_min: The lowest blood urea nitrogen concentration of the patient in their serum or plasma during the first hour of their unit stay;

- d1_glucose_max: The lowest blood urea nitrogen concentration of the patient in their serum or plasma during the first 24 hours of their unit stay;

- d1_glucose_min: The lowest bilirubin concentration of the patient in their serum or plasma during the first hour of their unit stay;

- d1_hco3_max: The lowest bilirubin concentration of the patient in their serum or plasma during the first 24 hours of their unit stay;

- d1_hco3_min: The lowest bicarbonate concentration for the patient in their serum or plasma during the first hour of their unit stay;

- d1_hemaglobin_max: The lowest bicarbonate concentration for the patient in their serum or plasma during the first 24 hours of their unit stay;

- d1_hemaglobin_min: The lowest arterial pH for the patient during the first hour of their unit stay;

- d1_hematocrit_max: The lowest arterial pH for the patient during the first 24 hours of their unit stay;

- d1_hematocrit_min: The lowest arterial partial pressure of oxygen for the patient during the first hour of their unit stay;

- d1_inr_max: The lowest arterial partial pressure of oxygen for the patient during the first 24 hours of their unit stay;

- d1_inr_min: The lowest arterial partial pressure of carbon dioxide for the patient during the first hour of their unit stay;

- d1_lactate_max: The lowest arterial partial pressure of carbon dioxide for the patient during the first 24 hours of their unit stay;

- d1_lactate_min: The lowest albumin concentration of the patient in their serum during the first hour of their unit stay;

- d1_platelets_max: The lowest albumin concentration of the patient in their serum during the first hour of their unit stay;

- d1_platelets_min: The lowest albumin concentration of the patient in their serum during the first 24 hours of their unit stay;

- d1_potassium_max: The lowest albumin concentration of the patient in their serum during the first 24 hours of their unit stay;

- d1_potassium_min: The location of the patient prior to being admitted to the unit;

- d1_sodium_max: The location of the patient prior to being admitted to the hospital;

- d1_sodium_min: The length of stay of the patient between hospital admission and unit admission;

- d1_wbc_max: The highest white blood cell count for the patient during the first hour of their unit stay;

- d1_wbc_min: The highest white blood cell count for the patient during the first 24 hours of their unit stay;

- h1_albumin_max: The highest volume proportion of red blood cells in a patient's blood during the first hour of their unit stay, expressed as a fraction;

- h1_albumin_min: The highest volume proportion of red blood cells in a patient's blood during the first 24 hours of their unit stay, expressed as a fraction;

- h1_bilirubin_max: The highest sodium concentration for the patient in their serum or plasma during the first hour of their unit stay;

- h1_bilirubin_min: The highest sodium concentration for the patient in their serum or plasma during the first 24 hours of their unit stay;

- h1_bun_max: The highest potassium concentration for the patient in their serum or plasma during the first hour of their unit stay;

- h1_bun_min: The highest potassium concentration for the patient in their serum or plasma during the first 24 hours of their unit stay;

- h1_calcium_max: The highest platelet count for the patient during the first hour of their unit stay;

- h1_calcium_min: The highest platelet count for the patient during the first 24 hours of their unit stay;

- h1_creatinine_max: The highest lactate concentration for the patient in their serum or plasma during the first hour of their unit stay;

- h1_creatinine_min: The highest lactate concentration for the patient in their serum or plasma during the first 24 hours of their unit stay;

- h1_glucose_max: The highest international normalized ratio for the patient during the first hour of their unit stay;

- h1_glucose_min: The highest international normalized ratio for the patient during the first 24 hours of their unit stay;

- h1_hco3_max: The highest hemoglobin concentration for the patient during the first hour of their unit stay;

- h1_hco3_min: The highest hemoglobin concentration for the patient during the first 24 hours of their unit stay;

- h1_hemaglobin_max: The highest glucose concentration of the patient in their serum or plasma during the first hour of their unit stay;

- h1_hemaglobin_min: The highest glucose concentration of the patient in their serum or plasma during the first 24 hours of their unit stay;

- h1_hematocrit_max: The highest fraction of inspired oxygen for the patient during the first hour of their unit stay;

- h1_hematocrit_min: The highest fraction of inspired oxygen for the patient during the first 24 hours of their unit stay;

- h1_inr_max: The highest creatinine concentration of the patient in their serum or plasma during the first hour of their unit stay;

- h1_inr_min: The highest creatinine concentration of the patient in their serum or plasma during the first 24 hours of their unit stay;

- h1_lactate_max: The highest calcium concentration of the patient in their serum during the first hour of their unit stay;

- h1_lactate_min: The highest calcium concentration of the patient in their serum during the first 24 hours of their unit stay;

- h1_platelets_max: The highest blood urea nitrogen concentration of the patient in their serum or plasma during the first hour of their unit stay;

- h1_platelets_min: The highest blood urea nitrogen concentration of the patient in their serum or plasma during the first 24 hours of their unit stay;

- h1_potassium_max: The highest bilirubin concentration of the patient in their serum or plasma during the first hour of their unit stay;

- h1_potassium_min: The highest bilirubin concentration of the patient in their serum or plasma during the first 24 hours of their unit stay;

- h1_sodium_max: The highest bicarbonate concentration for the patient in their serum or plasma during the first hour of their unit stay;

- h1_sodium_min: The highest bicarbonate concentration for the patient in their serum or plasma during the first 24 hours of their unit stay;

- h1_wbc_max: The highest arterial pH for the patient during the first hour of their unit stay;

- h1_wbc_min: The highest arterial pH for the patient during the first 24 hours of their unit stay;

- d1_arterial_pco2_max: The highest arterial partial pressure of oxygen for the patient during the first hour of their unit stay;

- d1_arterial_pco2_min: The highest arterial partial pressure of oxygen for the patient during the first 24 hours of their unit stay;

- d1_arterial_ph_max: The highest arterial partial pressure of carbon dioxide for the patient during the first hour of their unit stay;

- d1_arterial_ph_min: The highest arterial partial pressure of carbon dioxide for the patient during the first 24 hours of their unit stay;

- d1_arterial_po2_max: The hematocrit measured during the first 24 hours which results in the highest APACHE III score;

- d1_arterial_po2_min: The height of the person on unit admission;

- d1_pao2fio2ratio_max: The heart rate measured during the first 24 hours which results in the highest APACHE III score;

- d1_pao2fio2ratio_min: The glucose concentration measured during the first 24 hours which results in the highest APACHE III score;

- h1_arterial_pco2_max: The genotypical sex of the patient;

- h1_arterial_pco2_min: The fraction of inspired oxygen from the arterial blood gas taken during the first 24 hours of unit admission which produces the highest APACHE III score for oxygenation;

- h1_arterial_ph_max: The eye opening component of the Glasgow Coma Scale measured during the first 24 hours which results in the highest APACHE III score;

- h1_arterial_ph_min: The creatinine concentration measured during the first 24 hours which results in the highest APACHE III score;

- h1_arterial_po2_max: The common national or cultural tradition which the person belongs to;

- h1_arterial_po2_min: The body mass index of the person on unit admission;

- h1_pao2fio2ratio_max: The blood urea nitrogen concentration measured during the first 24 hours which results in the highest APACHE III score;

- h1_pao2fio2ratio_min: The bilirubin concentration measured during the first 24 hours which results in the highest APACHE III score;

- aids: The APACHE operative status; 1 for post-operative, 0 for non-operative;

- cirrhosis: The APACHE III-J sub-diagnosis code which best describes the reason for the ICU admission;

- hepatic_failure: The APACHE II diagnosis for the ICU admission;

- immunosuppression: The albumin concentration measured during the first 24 hours which results in the highest APACHE III score;

- leukemia: The age of the patient on unit admission;

- lymphoma: A unique identifier for the unit to which the patient was admitted;

- solid_tumor_with_metastasis: A classification which indicates the type of care the unit is capable of providing;

- diabetes_mellitus: Label;

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
TrainingWiDS2021_df = pd.read_csv("https://github.com/nelsondressler/DragonCaveDS/raw/master/widsdatathon2021/TrainingWiDS2021.csv")

TrainingWiDS2021_df.head()

   Unnamed: 0  encounter_id  ...  solid_tumor_with_metastasis  diabetes_mellitus
0           1        214826  ...                            0                  1
1           2        246060  ...                            0                  1
2           3        276985  ...                            0                  0
3           4        262220  ...                            0                  0
4           5        201746  ...                            0                  0

[5 rows x 181 columns]

In [9]:
TrainingWiDS2021_df.shape

(130157, 181)

In [16]:
TrainingWiDS2021_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130157 entries, 0 to 130156
Columns: 181 entries, Unnamed: 0 to diabetes_mellitus
dtypes: float64(157), int64(18), object(6)
memory usage: 179.7+ MB

In [13]:
TrainingWiDS2021_df.isnull().sum()

Unnamed: 0                        0
encounter_id                      0
hospital_id                       0
age                            4988
bmi                            4490
                               ...
immunosuppression                 0
leukemia                          0
lymphoma                          0
solid_tumor_with_metastasis       0
diabetes_mellitus                 0
Length: 181, dtype: int64

In [17]:
TrainingWiDS2021_df.describe()

          Unnamed: 0  ...  diabetes_mellitus
count  130157.000000  ...      130157.000000
mean    65079.000000  ...           0.216285
std     37573.233831  ...           0.411712
min         1.000000  ...           0.000000
25%     32540.000000  ...           0.000000
50%     65079.000000  ...           0.000000
75%     97618.000000  ...           0.000000
max    130157.000000  ...           1.000000

[8 rows x 175 columns]